PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE item
(
    item_id       integer not null
        constraint item_pk
            primary key autoincrement,
    item_name     text    not null,
    item_calories integer not null
);
INSERT INTO item VALUES(1,'apple',95);
INSERT INTO item VALUES(2,'banana',105);
INSERT INTO item VALUES(3,'strawberry',4);
INSERT INTO item VALUES(4,'avocado',234);
INSERT INTO item VALUES(5,'bell pepper',30);
INSERT INTO item VALUES(6,'carrot',25);
INSERT INTO item VALUES(7,'garlic',0);
INSERT INTO item VALUES(8,'lemon',17);
INSERT INTO item VALUES(9,'lime',20);
INSERT INTO item VALUES(10,'onion',44);
INSERT INTO item VALUES(11,'parsley',1);
INSERT INTO item VALUES(12,'cilantro',4);
INSERT INTO item VALUES(13,'potato',163);
INSERT INTO item VALUES(14,'spinach',7);
INSERT INTO item VALUES(15,'tomato',4);
INSERT INTO item VALUES(16,'breadcrumb',427);
INSERT INTO item VALUES(17,'pasta',76);
INSERT INTO item VALUES(18,'quinoa',222);
INSERT INTO item VALUES(19,'rice',206);
INSERT INTO item VALUES(20,'wheat bread',69);
INSERT INTO item VALUES(21,'flour tortilla',147);
INSERT INTO item VALUES(22,'chicken',335);
INSERT INTO item VALUES(23,'egg',78);
INSERT INTO item VALUES(24,'ground beef',1000);
INSERT INTO item VALUES(25,'lunch meat',99);
INSERT INTO item VALUES(26,'butter',102);
INSERT INTO item VALUES(27,'sliced cheese',104);
INSERT INTO item VALUES(28,'shredded cheese',113);
INSERT INTO item VALUES(29,'milk',103);
INSERT INTO item VALUES(30,'sour cream',23);
INSERT INTO item VALUES(31,'greek yogurt',100);
INSERT INTO item VALUES(32,'baking powder',2);
INSERT INTO item VALUES(33,'baking soda',0);
INSERT INTO item VALUES(34,'sugar',9);
INSERT INTO item VALUES(35,'brown sugar',17);
INSERT INTO item VALUES(36,'flour',455);
INSERT INTO item VALUES(37,'honey',64);
INSERT INTO item VALUES(38,'vanilla',38);
INSERT INTO item VALUES(39,'dry yeast',23);
INSERT INTO item VALUES(40,'chocolate chips',2);
INSERT INTO item VALUES(41,'cocoa powder',12);
INSERT INTO item VALUES(42,'powdered sugar',31);
INSERT INTO item VALUES(43,'blueberry',1);
INSERT INTO item VALUES(44,'corn',90);
INSERT INTO item VALUES(45,'broccoli',34);
INSERT INTO item VALUES(46,'pizza',285);
INSERT INTO item VALUES(47,'beef',213);
INSERT INTO item VALUES(48,'bacon',43);
INSERT INTO item VALUES(49,'shrimp',99);
INSERT INTO item VALUES(50,'salsa',36);
INSERT INTO item VALUES(51,'peanut butter',188);
INSERT INTO item VALUES(52,'cereal',307);
INSERT INTO item VALUES(53,'soup',158);
INSERT INTO item VALUES(54,'tuna',203);
CREATE TABLE IF NOT EXISTS "expiration"
(
    item_id         integer not null
        references item,
    storage_method  text    default 'room' not null,
    expiration_days integer default 0
);
INSERT INTO expiration VALUES(1,'room',7);
INSERT INTO expiration VALUES(1,'freeze',28);
INSERT INTO expiration VALUES(1,'frozen',360);
INSERT INTO expiration VALUES(2,'room',4);
INSERT INTO expiration VALUES(2,'freeze',7);
INSERT INTO expiration VALUES(2,'frozen',60);
INSERT INTO expiration VALUES(3,'room',2);
INSERT INTO expiration VALUES(3,'freeze',4);
INSERT INTO expiration VALUES(3,'frozen',300);
INSERT INTO expiration VALUES(4,'room',3);
INSERT INTO expiration VALUES(4,'freeze',5);
INSERT INTO expiration VALUES(4,'frozen',180);
INSERT INTO expiration VALUES(5,'room',5);
INSERT INTO expiration VALUES(5,'freeze',14);
INSERT INTO expiration VALUES(5,'frozen',360);
INSERT INTO expiration VALUES(6,'room',3);
INSERT INTO expiration VALUES(6,'freeze',21);
INSERT INTO expiration VALUES(6,'frozen',360);
INSERT INTO expiration VALUES(7,'room',90);
INSERT INTO expiration VALUES(7,'freeze',180);
INSERT INTO expiration VALUES(7,'frozen',180);
INSERT INTO expiration VALUES(8,'room',7);
INSERT INTO expiration VALUES(8,'freeze',14);
INSERT INTO expiration VALUES(8,'frozen',90);
INSERT INTO expiration VALUES(9,'room',7);
INSERT INTO expiration VALUES(9,'freeze',14);
INSERT INTO expiration VALUES(9,'frozen',90);
INSERT INTO expiration VALUES(10,'room',90);
INSERT INTO expiration VALUES(10,'freeze',240);
INSERT INTO expiration VALUES(10,'frozen',240);
INSERT INTO expiration VALUES(11,'room',7);
INSERT INTO expiration VALUES(11,'freeze',30);
INSERT INTO expiration VALUES(11,'frozen',120);
INSERT INTO expiration VALUES(12,'room',1);
INSERT INTO expiration VALUES(12,'freeze',7);
INSERT INTO expiration VALUES(12,'frozen',60);
INSERT INTO expiration VALUES(13,'room',7);
INSERT INTO expiration VALUES(13,'freeze',21);
INSERT INTO expiration VALUES(13,'frozen',300);
INSERT INTO expiration VALUES(14,'room',1);
INSERT INTO expiration VALUES(14,'freeze',7);
INSERT INTO expiration VALUES(14,'frozen',300);
INSERT INTO expiration VALUES(15,'room',3);
INSERT INTO expiration VALUES(15,'freeze',14);
INSERT INTO expiration VALUES(15,'frozen',360);
INSERT INTO expiration VALUES(16,'room',300);
INSERT INTO expiration VALUES(16,'freeze',300);
INSERT INTO expiration VALUES(16,'frozen',360);
INSERT INTO expiration VALUES(17,'room',1);
INSERT INTO expiration VALUES(17,'freeze',3);
INSERT INTO expiration VALUES(17,'frozen',180);
INSERT INTO expiration VALUES(18,'room',480);
INSERT INTO expiration VALUES(18,'freeze',480);
INSERT INTO expiration VALUES(18,'frozen',480);
INSERT INTO expiration VALUES(19,'room',800);
INSERT INTO expiration VALUES(19,'freeze',800);
INSERT INTO expiration VALUES(19,'frozen',800);
INSERT INTO expiration VALUES(20,'room',3);
INSERT INTO expiration VALUES(20,'freeze',7);
INSERT INTO expiration VALUES(20,'frozen',90);
INSERT INTO expiration VALUES(21,'room',7);
INSERT INTO expiration VALUES(21,'freeze',180);
INSERT INTO expiration VALUES(21,'frozen',180);
INSERT INTO expiration VALUES(22,'room',1);
INSERT INTO expiration VALUES(22,'freeze',360);
INSERT INTO expiration VALUES(22,'frozen',600);
INSERT INTO expiration VALUES(23,'room',1);
INSERT INTO expiration VALUES(23,'freeze',360);
INSERT INTO expiration VALUES(23,'frozen',360);
INSERT INTO expiration VALUES(24,'room',1);
INSERT INTO expiration VALUES(24,'freeze',120);
INSERT INTO expiration VALUES(24,'frozen',360);
INSERT INTO expiration VALUES(25,'room',1);
INSERT INTO expiration VALUES(25,'freeze',360);
INSERT INTO expiration VALUES(25,'frozen',600);
INSERT INTO expiration VALUES(26,'room',2);
INSERT INTO expiration VALUES(26,'freeze',120);
INSERT INTO expiration VALUES(26,'frozen',360);
INSERT INTO expiration VALUES(27,'room',1);
INSERT INTO expiration VALUES(27,'freeze',240);
INSERT INTO expiration VALUES(27,'frozen',360);
INSERT INTO expiration VALUES(28,'room',1);
INSERT INTO expiration VALUES(28,'freeze',240);
INSERT INTO expiration VALUES(28,'frozen',360);
INSERT INTO expiration VALUES(29,'room',1);
INSERT INTO expiration VALUES(29,'freeze',8);
INSERT INTO expiration VALUES(29,'frozen',180);
INSERT INTO expiration VALUES(30,'room',1);
INSERT INTO expiration VALUES(30,'freeze',60);
INSERT INTO expiration VALUES(30,'frozen',60);
INSERT INTO expiration VALUES(31,'room',1);
INSERT INTO expiration VALUES(31,'freeze',180);
INSERT INTO expiration VALUES(31,'frozen',180);
INSERT INTO expiration VALUES(32,'room',180);
INSERT INTO expiration VALUES(32,'freeze',180);
INSERT INTO expiration VALUES(32,'frozen',180);
INSERT INTO expiration VALUES(33,'room',360);
INSERT INTO expiration VALUES(33,'freeze',360);
INSERT INTO expiration VALUES(33,'frozen',360);
INSERT INTO expiration VALUES(34,'room',720);
INSERT INTO expiration VALUES(34,'freeze',720);
INSERT INTO expiration VALUES(34,'frozen',720);
INSERT INTO expiration VALUES(35,'room',720);
INSERT INTO expiration VALUES(35,'freeze',720);
INSERT INTO expiration VALUES(35,'frozen',720);
INSERT INTO expiration VALUES(36,'room',180);
INSERT INTO expiration VALUES(36,'freeze',360);
INSERT INTO expiration VALUES(36,'frozen',720);
INSERT INTO expiration VALUES(37,'room',600);
INSERT INTO expiration VALUES(37,'freeze',600);
INSERT INTO expiration VALUES(37,'frozen',600);
INSERT INTO expiration VALUES(38,'room',600);
INSERT INTO expiration VALUES(38,'freeze',600);
INSERT INTO expiration VALUES(38,'frozen',600);
INSERT INTO expiration VALUES(39,'room',360);
INSERT INTO expiration VALUES(39,'freeze',360);
INSERT INTO expiration VALUES(39,'frozen',360);
INSERT INTO expiration VALUES(40,'room',720);
INSERT INTO expiration VALUES(40,'freeze',720);
INSERT INTO expiration VALUES(40,'frozen',720);
INSERT INTO expiration VALUES(41,'room',1080);
INSERT INTO expiration VALUES(41,'freeze',1080);
INSERT INTO expiration VALUES(41,'frozen',1080);
INSERT INTO expiration VALUES(42,'room',1800);
INSERT INTO expiration VALUES(42,'freeze',1800);
INSERT INTO expiration VALUES(42,'frozen',1800);
INSERT INTO expiration VALUES(43,'room',1);
INSERT INTO expiration VALUES(43,'freeze',6);
INSERT INTO expiration VALUES(43,'frozen',12);
INSERT INTO expiration VALUES(44,'room',2);
INSERT INTO expiration VALUES(44,'freeze',4);
INSERT INTO expiration VALUES(44,'frozen',240);
INSERT INTO expiration VALUES(45,'room',1);
INSERT INTO expiration VALUES(45,'freeze',5);
INSERT INTO expiration VALUES(45,'frozen',360);
INSERT INTO expiration VALUES(46,'room',1);
INSERT INTO expiration VALUES(46,'freeze',30);
INSERT INTO expiration VALUES(46,'frozen',360);
INSERT INTO expiration VALUES(47,'room',1);
INSERT INTO expiration VALUES(47,'freeze',120);
INSERT INTO expiration VALUES(47,'frozen',360);
INSERT INTO expiration VALUES(48,'room',1);
INSERT INTO expiration VALUES(48,'freeze',180);
INSERT INTO expiration VALUES(48,'frozen',240);
INSERT INTO expiration VALUES(49,'room',1);
INSERT INTO expiration VALUES(49,'freeze',180);
INSERT INTO expiration VALUES(49,'frozen',300);
INSERT INTO expiration VALUES(50,'room',1);
INSERT INTO expiration VALUES(50,'freeze',60);
INSERT INTO expiration VALUES(50,'frozen',120);
INSERT INTO expiration VALUES(51,'room',30);
INSERT INTO expiration VALUES(51,'freeze',180);
INSERT INTO expiration VALUES(51,'frozen',180);
INSERT INTO expiration VALUES(52,'room',60);
INSERT INTO expiration VALUES(52,'freeze',180);
INSERT INTO expiration VALUES(52,'frozen',180);
INSERT INTO expiration VALUES(53,'room',1);
INSERT INTO expiration VALUES(53,'freeze',90);
INSERT INTO expiration VALUES(53,'frozen',90);
INSERT INTO expiration VALUES(54,'room',1);
INSERT INTO expiration VALUES(54,'freeze',2);
INSERT INTO expiration VALUES(54,'frozen',90);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('item',54);
CREATE UNIQUE INDEX item_item_id_uindex
    on item (item_id);
CREATE UNIQUE INDEX item_item_name_uindex
    on item (item_name);
COMMIT;
